Develop
TakumiUchida/takumi-uchida-codereview pull request #7
Opened 2020-09-21 04:21 UTC by TakumiUchida

2020-09-21 14:14 UTC, myzktkyk requested changes
動作は問題ないのですが、1点セキュリティ面で指摘をしております。

2020-09-21 14:14 UTC, myzktkyk commented on javascript課題③-3.html
> +  html += `<tr id="nowWorking"><td>${i}</td><td>${tasks[i]}</td><td><input type="button" id="working${i}" value="作業中"><input type="button" class="delete" value="削除"></td></tr>`;
動作としては問題ないのですが、このままだと XSS 脆弱性があります
以下の様な入力をされるとその通り動いてしまいます。
`<img src=x onerror="alert('XSS Attack')">`

https://www.shadan-kun.com/blog/measure/1052/#:~:text=%E3%82%AF%E3%83%AD%E3%82%B9%E3%82%B5%E3%82%A4%E3%83%88%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%EF%BC%88XSS%EF%BC%89%E3%81%A8%E3%81%AF%E3%80%81%E6%8E%B2%E7%A4%BA%E6%9D%BF%E3%82%B5%E3%82%A4%E3%83%88%E3%82%84,%E3%81%AE%E7%BD%A0%E3%82%92%E4%BB%95%E6%8E%9B%E3%81%91%E3%81%BE%E3%81%99%E3%80%82

2020-09-25 20:23 UTC, kouki-iwahara commented on javascript課題③-3.html
> +  html += `<tr id="nowWorking"><td>${i}</td><td>${escapeHTML(tasks[i])}</td><td><input type="button" id="working${i}" value="作業中"><input type="button" class="delete" value="削除"></td></tr>`;
テキストでhtmlを流しこむとJSで操作しづらくなるので、要素はcreateElementで作成しましょう。
https://developer.mozilla.org/ja/docs/Web/API/Document/createElement

2020-09-28 10:50 UTC, myzktkyk approved these changes

2020-09-29 08:21 UTC, merged